//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPA_Explorer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPA_Explorer.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive file location: .
        /// </summary>
        internal static string EN_Archive_file_location {
            get {
                return ResourceManager.GetString("EN_Archive_file_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive file size: .
        /// </summary>
        internal static string EN_Archive_file_size {
            get {
                return ResourceManager.GetString("EN_Archive_file_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive modified.
        /// </summary>
        internal static string EN_Archive_modified {
            get {
                return ResourceManager.GetString("EN_Archive_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive was modified, do you really want to exit without saving and lose changes?.
        /// </summary>
        internal static string EN_Archive_modified_close {
            get {
                return ResourceManager.GetString("EN_Archive_modified_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive was modified, do you really want to load a new one and lose changes?.
        /// </summary>
        internal static string EN_Archive_modified_load {
            get {
                return ResourceManager.GetString("EN_Archive_modified_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive was modified, do you really want to create a new one and lose changes?.
        /// </summary>
        internal static string EN_Archive_modified_new {
            get {
                return ResourceManager.GetString("EN_Archive_modified_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string EN_Archive_save_cancel {
            get {
                return ResourceManager.GetString("EN_Archive_save_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string EN_Archive_save_continue {
            get {
                return ResourceManager.GetString("EN_Archive_save_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data padding:.
        /// </summary>
        internal static string EN_Archive_save_padding {
            get {
                return ResourceManager.GetString("EN_Archive_save_padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data step:.
        /// </summary>
        internal static string EN_Archive_save_step {
            get {
                return ResourceManager.GetString("EN_Archive_save_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive options.
        /// </summary>
        internal static string EN_Archive_save_title {
            get {
                return ResourceManager.GetString("EN_Archive_save_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive version:.
        /// </summary>
        internal static string EN_Archive_save_version {
            get {
                return ResourceManager.GetString("EN_Archive_save_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive version: .
        /// </summary>
        internal static string EN_Archive_version {
            get {
                return ResourceManager.GetString("EN_Archive_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel operation.
        /// </summary>
        internal static string EN_Cancel_operation {
            get {
                return ResourceManager.GetString("EN_Cancel_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new archive.
        /// </summary>
        internal static string EN_Create_new_archive {
            get {
                return ResourceManager.GetString("EN_Create_new_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty archive.
        /// </summary>
        internal static string EN_Empty_archive {
            get {
                return ResourceManager.GetString("EN_Empty_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive does not contain any files, cannot save empty archive..
        /// </summary>
        internal static string EN_Empty_archive_save {
            get {
                return ResourceManager.GetString("EN_Empty_archive_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RenPy Archive Explorer.
        /// </summary>
        internal static string EN_Explorer_title {
            get {
                return ResourceManager.GetString("EN_Explorer_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export checked.
        /// </summary>
        internal static string EN_Export_checked {
            get {
                return ResourceManager.GetString("EN_Export_checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting file: .
        /// </summary>
        internal static string EN_Exporting_file {
            get {
                return ResourceManager.GetString("EN_Exporting_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File list:.
        /// </summary>
        internal static string EN_File_list {
            get {
                return ResourceManager.GetString("EN_File_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string EN_Image {
            get {
                return ResourceManager.GetString("EN_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index file location: .
        /// </summary>
        internal static string EN_Index_file_location {
            get {
                return ResourceManager.GetString("EN_Index_file_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index file size: .
        /// </summary>
        internal static string EN_Index_file_size {
            get {
                return ResourceManager.GetString("EN_Index_file_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid values.
        /// </summary>
        internal static string EN_Invalid_values {
            get {
                return ResourceManager.GetString("EN_Invalid_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langauge:.
        /// </summary>
        internal static string EN_Language {
            get {
                return ResourceManager.GetString("EN_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load file.
        /// </summary>
        internal static string EN_Load_file {
            get {
                return ResourceManager.GetString("EN_Load_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load RenPy Archive.
        /// </summary>
        internal static string EN_Load_RenPy_Archive {
            get {
                return ResourceManager.GetString("EN_Load_RenPy_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading archive after saving failed which indicates corrupted archive. Attempting to restore changes from before save..
        /// </summary>
        internal static string EN_Loading_archive_after_saving_failed {
            get {
                return ResourceManager.GetString("EN_Loading_archive_after_saving_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file: .
        /// </summary>
        internal static string EN_Loading_file {
            get {
                return ResourceManager.GetString("EN_Loading_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        internal static string EN_Media {
            get {
                return ResourceManager.GetString("EN_Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string EN_None {
            get {
                return ResourceManager.GetString("EN_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects count: .
        /// </summary>
        internal static string EN_Objects_count {
            get {
                return ResourceManager.GetString("EN_Objects_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string EN_Pause {
            get {
                return ResourceManager.GetString("EN_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string EN_Play {
            get {
                return ResourceManager.GetString("EN_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview is not supported for this file..
        /// </summary>
        internal static string EN_Preview_is_not_supported {
            get {
                return ResourceManager.GetString("EN_Preview_is_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string EN_Ready {
            get {
                return ResourceManager.GetString("EN_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove checked.
        /// </summary>
        internal static string EN_Remove_checked {
            get {
                return ResourceManager.GetString("EN_Remove_checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPA/RPI files.
        /// </summary>
        internal static string EN_RPA_RPI_files {
            get {
                return ResourceManager.GetString("EN_RPA_RPI_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save archive.
        /// </summary>
        internal static string EN_Save_archive {
            get {
                return ResourceManager.GetString("EN_Save_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed.
        /// </summary>
        internal static string EN_Save_failed {
            get {
                return ResourceManager.GetString("EN_Save_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save RenPy Archive.
        /// </summary>
        internal static string EN_Save_RenPy_Archive {
            get {
                return ResourceManager.GetString("EN_Save_RenPy_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving archive....
        /// </summary>
        internal static string EN_Saving_archive {
            get {
                return ResourceManager.GetString("EN_Saving_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected object size: .
        /// </summary>
        internal static string EN_Selected_object_size {
            get {
                return ResourceManager.GetString("EN_Selected_object_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string EN_Text {
            get {
                return ResourceManager.GetString("EN_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved objects count: .
        /// </summary>
        internal static string EN_Unsaved_objects_count {
            get {
                return ResourceManager.GetString("EN_Unsaved_objects_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file from list on the side to preview contents. Check and export to save it locally..
        /// </summary>
        internal static string EN_Usage_instructions_loaded {
            get {
                return ResourceManager.GetString("EN_Usage_instructions_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start by creating/loading archive file or drag and drop archive file to this window to load it..
        /// </summary>
        internal static string EN_Usage_instructions_new {
            get {
                return ResourceManager.GetString("EN_Usage_instructions_new", resourceCulture);
            }
        }
    }
}
