//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPA_Explorer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPA_Explorer.Strings_EN", typeof(Strings_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid values.
        /// </summary>
        internal static string ArchiveSave_button1_Click_Invalid_values {
            get {
                return ResourceManager.GetString("ArchiveSave_button1_Click_Invalid_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive does not contain any files, cannot save empty archive..
        /// </summary>
        internal static string RpaExplorer_button7_Click_Archive_does_not_contain_any_files__cannot_save_empty_archive_ {
            get {
                return ResourceManager.GetString("RpaExplorer_button7_Click_Archive_does_not_contain_any_files__cannot_save_empty_a" +
                        "rchive_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty archive.
        /// </summary>
        internal static string RpaExplorer_button7_Click_Empty_archive {
            get {
                return ResourceManager.GetString("RpaExplorer_button7_Click_Empty_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading archive after saving failed which indicates corrupted archive. Attempting to restore changes from before save..
        /// </summary>
        internal static string RpaExplorer_button7_Click_Loading_archive_after_saving_failed_which_indicates_corrupted_archive__Attempting_to_restore_changes_from_before_save_ {
            get {
                return ResourceManager.GetString("RpaExplorer_button7_Click_Loading_archive_after_saving_failed_which_indicates_cor" +
                        "rupted_archive__Attempting_to_restore_changes_from_before_save_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed.
        /// </summary>
        internal static string RpaExplorer_button7_Click_Save_failed {
            get {
                return ResourceManager.GetString("RpaExplorer_button7_Click_Save_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save RenPy Archive.
        /// </summary>
        internal static string RpaExplorer_button7_Click_Save_RenPy_Archive {
            get {
                return ResourceManager.GetString("RpaExplorer_button7_Click_Save_RenPy_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving archive....
        /// </summary>
        internal static string RpaExplorer_button7_Click_Saving_archive___ {
            get {
                return ResourceManager.GetString("RpaExplorer_button7_Click_Saving_archive___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive modified.
        /// </summary>
        internal static string RpaExplorer_CheckIfChanged_Archive_modified {
            get {
                return ResourceManager.GetString("RpaExplorer_CheckIfChanged_Archive_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive was modified, do you really want to create a new one and lose changes?.
        /// </summary>
        internal static string RpaExplorer_CreateNewArchive_Archive_modified {
            get {
                return ResourceManager.GetString("RpaExplorer_CreateNewArchive_Archive_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting file: .
        /// </summary>
        internal static string RpaExplorer_exportFiles_Exporting_file__ {
            get {
                return ResourceManager.GetString("RpaExplorer_exportFiles_Exporting_file__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive was modified, do you really want to exit without saving and lose changes?.
        /// </summary>
        internal static string RpaExplorer_FormClosing_Archive_modified {
            get {
                return ResourceManager.GetString("RpaExplorer_FormClosing_Archive_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive was modified, do you really want to load a new one and lose changes?.
        /// </summary>
        internal static string RpaExplorer_LoadArchive_Archive_modified {
            get {
                return ResourceManager.GetString("RpaExplorer_LoadArchive_Archive_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file from list on the side to preview contents. Check and export to save it locally..
        /// </summary>
        internal static string RpaExplorer_LoadArchive_Choose_file_from_list_on_the_side_to_preview_contents__Check_and_export_to_save_it_locally_ {
            get {
                return ResourceManager.GetString("RpaExplorer_LoadArchive_Choose_file_from_list_on_the_side_to_preview_contents__Ch" +
                        "eck_and_export_to_save_it_locally_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file: .
        /// </summary>
        internal static string RpaExplorer_LoadArchive_Loading_file__ {
            get {
                return ResourceManager.GetString("RpaExplorer_LoadArchive_Loading_file__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load RenPy Archive.
        /// </summary>
        internal static string RpaExplorer_LoadArchive_Select_RenPy_Archive {
            get {
                return ResourceManager.GetString("RpaExplorer_LoadArchive_Select_RenPy_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string RpaExplorer_Pause {
            get {
                return ResourceManager.GetString("RpaExplorer_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string RpaExplorer_Play {
            get {
                return ResourceManager.GetString("RpaExplorer_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview is not supported for this file..
        /// </summary>
        internal static string RpaExplorer_PreviewSelectedItem_Preview_is_not_supported_for_this_file_ {
            get {
                return ResourceManager.GetString("RpaExplorer_PreviewSelectedItem_Preview_is_not_supported_for_this_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string RpaExplorer_Ready {
            get {
                return ResourceManager.GetString("RpaExplorer_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPA/RPI files (*.rpa,*.rpi)|*.rpa;*.rpi.
        /// </summary>
        internal static string RpaExplorer_RPA_RPI_files {
            get {
                return ResourceManager.GetString("RpaExplorer_RPA_RPI_files", resourceCulture);
            }
        }
    }
}
